require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.0
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - vendor/**/*

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  CountComments: true
  Max: 25
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - "config/**/*"
    - "test/**/*"
