name: Main

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
          CI: true
        run: docker-compose --file docker-compose.ci.yml run ci bash -c 'make init-db && make tests'

      - name: Check coverage existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "coverage/lcov.info, ./coverage/lcov.info"

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
