name: Main

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  check_branch:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose --file docker-compose.ci.yml build

      - name: Prepare test env
        env:
          RAILS_ENV: test
        run: docker-compose --file docker-compose.ci.yml run ci make init-db

      - name: Lint
        run: docker-compose --file docker-compose.ci.yml run ci bundle exec rubocop

      - name: Run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
        run: docker-compose --file docker-compose.ci.yml run ci bundle exec rails test

      - name: Archive coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: |
            coverage

      - name: Send report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
